# Generated by Django 5.2.13 on 2026-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_ugx',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in UGX (Ugandan Shilling)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=10),
        ),
    ]
