# Generated by Django 5.2.13 on 2026-04-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_price_product_price_ugx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units currently available for sale'),
        ),
    ]
